version: '3'

services:
  call-logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: call-logger
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_URL=sqlite+aiosqlite:///data/phone_calls.db
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false

  syslog: # needed for extra logging from Yealink and Cisco phones
    image: balabit/syslog-ng:latest
    container_name: syslog-server
    restart: unless-stopped
    ports:
      - "5514:514/udp"  # Custom UDP port for syslog
      - "5514:514/tcp"  # Custom TCP port for syslog
    volumes:
      - ./logs:/var/log  # Where logs will be stored
    command: -edv  # Run in verbose mode

